name: lakbay_kasaysayan_ai
description: A Filipino history tutor built with Flutter and natural Filipino voice support.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  just_audio: ^0.9.40
  speech_to_text: ^7.0.0
  supabase_flutter: ^2.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/lakbay_lolo.svg
